Fix if?/then?/else? types and add tests
ostrowr/ts-json-validator pull request #45
Opened 2021-01-08 21:42 UTC by drtyh2o

@ostrowr I took a stab at resolving the issues I was having with issue #44. Feel free to make any necessary adjustments.

2021-01-08 21:46 UTC, drtyh2o commented on package-lock.json
> +      "optional": true
These changes to `package-lock.json` were the result of my running `npm install` after cloning the repo.

2021-01-09 00:32 UTC, ostrowr commented
Oh! Thanks so much for taking care of this!

2021-01-09 00:34 UTC, ostrowr requested changes
Thanks so much! Do you mind adding a test for just if/then with no /else? (I'm happy to take it over if you've had enough)

Otherwise, this looks good. Thanks for tracking this down; I imagine it must have been a bit of a slog...

2021-01-09 00:45 UTC, drtyh2o commented
As long as you’re ok with the fundamental change to the underlying types I proposed, I can add a test for if/then. It should be just a subset of the if/then/else tests I added, although I might try testing an array of if/then (no else) schemas within an allOf for fun. :-)

2021-01-09 01:32 UTC, ostrowr commented
> As long as you’re ok with the fundamental change to the underlying types I proposed, I can add a test for if/then. It should be just a subset of the if/then/else tests I added, although I might try testing an array of if/then (no else) schemas within an allOf for fun. :-)

Yes, definitely. It looks like the old types were just a bug. Changes to package-lock are OK too.

2021-01-11 15:51 UTC, drtyh2o commented
@ostrowr I think this is ready now. Will you have time to review, merge, and publish a new version?

2021-01-11 19:26 UTC, ostrowr approved these changes
lgtm! I'll publish shortly.

2021-01-11 19:26 UTC, merged